### ISSUE TITLE
Configuration() object is missing the access_token attribute

### ISSUE THREAD

**Issue by eyalmadar** [pdfgeneratorapi/python-client#1]
Hi, 
Great python package and an excellent README file!

I was trying to implement the document API and saw an issue with the Configuration() object that I wanted to check with you about.
The Configuration() should get the `access_token` for holding the JWT token in the docs, but the object's `__init__` does not expose this attribute.
From the doc:
```
configuration = pdf_generator_api_client.Configuration(
    access_token = 'YOUR_BEARER_TOKEN'
)
```

Is this a bug, or is there a way to override this issue?
For now, I used `super()` and added it to my local code class(), but I wonder if this is the correct approach.

Thanks!

**Comment by spacether** [comment]
fyi if the version of the autogen python client is increased, access_token will be added.
One can see it working here:
https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/samples/openapi3/client/features/security/python/test_manual/test_paths/test_path_with_two_explicit_security/test_get.py#L36
```
    security_scheme_info: api_configuration.SecuritySchemeInfo = {
        # security_scheme_info for security_index 1
        "bearer_test": security_scheme_bearer_test.BearerTest(
            access_token='someAccessToken'
        ),
    }
    api_config = api_configuration.ApiConfiguration(
        security_scheme_info=security_scheme_info
    )
```
